nota_1 = int(input("Ingresa la primer nota"))
nota_2 = int(input("Ingresa la segunda nota"))
nota_3 = int(input("Ingresa la tercer nota"))
nota_4 = int(input("Ingresa la cuarta nota"))
promedio = float((nota_1 + nota_2 + nota_3 + nota_4)/4)
print("El promedio de tus notas es ", promedio)